fn main() {
    // The app's own commands (chat-voice §13.2). Listing them generates their
    // `allow-*`/`deny-*` permissions (into permissions/autogenerated, which
    // is not tracked); capabilities/remote-ui.json grants the allow ones to
    // the gateway page. A command missing here is refused to the page.
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&["audio_outputs", "audio_output_set"]),
    ))
    .expect("tauri build script");
}
