//! `ops-builds`: container builds and the local podman image store
//! (api-docs design §4.7, container-builds design §15). The 19 typed
//! Backends ops: each takes an api-types `*Args` struct and answers an
//! api-types response — `web/api.rs:1007-1038`, `ops/backends.rs:148-620`.

use lmgw_api_types::builds as dto;

use super::{OpArgs, OpDoc, Resp};

const TAG: &str = "ops-builds";

pub(super) const OPS: &[OpDoc] = &[
    OpDoc {
        name: "builds",
        tag: TAG,
        summary: "List every container build, with its newest run and update badge",
        description: None,
        tool: Some("lmgw__builds"),
        args: OpArgs::NoArgs,
        response: Resp::Json(|g| g.root_schema_for::<dto::BuildsResponse>()),
        writes: false,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "build_get",
        tag: TAG,
        summary: "One build's detail plus a page of its run history",
        description: Some(
            "One build's row plus a page of its runs, newest first. `limit` is the page size \
             (absent means every run); `before` is an exclusive run-id cursor.",
        ),
        tool: None,
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::BuildsGetArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::BuildGetResponse>()),
        writes: false,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "build_set",
        tag: TAG,
        summary: "Create, update, delete or duplicate a container build definition",
        description: None,
        tool: Some("lmgw__build_set"),
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::BuildSetArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::BuildSetResponse>()),
        writes: true,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "build_resolve",
        tag: TAG,
        summary: "Preview what an unsaved build spec resolves to, without building",
        description: Some(
            "What a spec resolves to right now — commits, tags — fetched but not built. The \
             build editor's \"Resolve\" button.",
        ),
        tool: None,
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::BuildResolveArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::ResolvedPreview>()),
        writes: false,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "build_check_merge",
        tag: TAG,
        summary: "Check whether a build's extras merge cleanly onto its ref, without building",
        description: None,
        tool: Some("lmgw__build_check_merge"),
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::BuildCheckMergeArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::CheckMergeReport>()),
        writes: true,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "build_run",
        tag: TAG,
        summary: "Start a build run",
        description: None,
        tool: Some("lmgw__build_run"),
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::BuildRunArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::BuildRunStarted>()),
        writes: true,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "build_run_log",
        tag: TAG,
        summary: "Read a byte-offset or tail chunk of a run's log",
        description: Some(
            "A chunk of a run's log (at most 1 MiB per call), from a byte offset, or its last \
             `tail` lines — not both. The reply's next_offset continues a following call.",
        ),
        tool: None,
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::BuildRunLogArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::RunLogChunk>()),
        writes: false,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "build_promote",
        tag: TAG,
        summary: "Move a build's moving tag to one of its runs (\"Make current\")",
        description: None,
        tool: None,
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::BuildPromoteArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::PromoteResponse>()),
        writes: true,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "build_verify",
        tag: TAG,
        summary: "Re-run the GPU verify checks for a built-but-unverified run",
        description: None,
        tool: None,
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::BuildVerifyArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::VerifyReport>()),
        writes: true,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "build_env",
        tag: TAG,
        summary: "What the build editor needs when it opens",
        description: None,
        tool: None,
        args: OpArgs::NoArgs,
        response: Resp::Json(|g| g.root_schema_for::<dto::BuildEnv>()),
        writes: false,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "forge_refs",
        tag: TAG,
        summary: "List a repository's branches and tags",
        description: Some("The remote's branches and tags, for the ref combobox."),
        tool: None,
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::ForgeRefsArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::RemoteRefsView>()),
        writes: false,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "forge_prs",
        tag: TAG,
        summary: "List a repository's open pull/merge requests",
        description: None,
        tool: Some("lmgw__forge_prs"),
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::ForgePrsArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::ForgePrPage>()),
        writes: false,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "forge_pr",
        tag: TAG,
        summary: "One pull/merge request's current forge state",
        description: None,
        tool: None,
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::ForgePrArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::ForgePr>()),
        writes: false,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "container_images",
        tag: TAG,
        summary: "List every local podman image of the three engines",
        description: None,
        tool: Some("lmgw__container_images"),
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::ContainerImagesArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::ContainerImagesResponse>()),
        writes: false,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "container_image_delete",
        tag: TAG,
        summary: "Delete a local podman image by tag or id",
        description: None,
        tool: Some("lmgw__container_image_delete"),
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::ContainerImageDeleteArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::ContainerImageDeleteResponse>()),
        writes: true,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "container_image_tag",
        tag: TAG,
        summary: "Add and/or remove one tag on a local image",
        description: None,
        tool: None,
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::ContainerImageTagArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::ContainerImageTagResponse>()),
        writes: true,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "build_updates_check",
        tag: TAG,
        summary: "Check now whether a build's branch or PRs have moved",
        description: Some(
            "Ask the remotes now for one build (`id`), or every build and every registry image \
             in use. A build with no succeeded or unverified run has nothing to compare with.",
        ),
        tool: None,
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::BuildUpdatesCheckArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::BuildUpdatesResponse>()),
        writes: false,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "container_image_pull",
        tag: TAG,
        summary: "Pull a registry image's update as a background job",
        description: None,
        tool: None,
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::ContainerImagePullArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::ContainerImagePullStarted>()),
        writes: true,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
    OpDoc {
        name: "container_image_pull_status",
        tag: TAG,
        summary: "Read a pull job's progress or result",
        description: Some(
            "What a `container_image_pull` job is doing, or did — the Pull update panel's \
             result and its \"recreate N running containers\" prompt.",
        ),
        tool: None,
        args: OpArgs::Struct(|g| g.root_schema_for::<dto::ContainerImagePullStatusArgs>()),
        response: Resp::Json(|g| g.root_schema_for::<dto::ContainerImagePullStatus>()),
        writes: false,
        reveals_secret: false,
        confirm_note: None,
        deprecated: false,
        example: None,
    },
];
