//! `lmgw-core`'s integration tests, folded into one binary.
//!
//! Cargo used to build each `tests/<name>.rs` file as its own binary, and
//! every one of them links the whole of `lmgw-core` (~450 MB in debug) — so a
//! one-line change to core relinked all 75 of them. Cargo auto-discovers
//! `tests/it/main.rs` as a single test target named `it`, so a core change
//! now links once instead of 75 times.
//!
//! Run one former file's tests with its module path, e.g.:
//!
//! ```sh
//! cargo test -p lmgw-core --test it vram_admission::
//! ```
//!
//! New test files go in as a new `mod <name>;` line below (alphabetical), with
//! the file at `tests/it/<name>.rs`.
//!
//! The one exception is `tests/trace_span.rs`, which installs a process-global
//! `tracing` subscriber and so needs a process of its own; see its header.

mod common;
mod support;

mod agent_stopped_rows;
mod agents_catalog;
mod agents_container;
mod agents_ledger;
mod agents_package;
mod agents_runs;
mod agents_script;
mod agents_self_view;
mod agents_service;
mod anthropic_beta;
mod audio_backend;
mod audio_catalog;
mod audio_catalog_live;
mod audio_catalog_pins;
mod audio_engine_errors;
mod audio_expressive;
mod audio_probes_live;
mod audio_residency_live;
mod audio_streaming;
mod audio_transcripts;
mod audio_voicedesign;
mod audio_voices_native;
mod aux_models;
mod aux_router;
mod backends;
mod backends_forge;
mod backends_git;
mod backends_ops;
mod backends_registry_live;
mod backends_run;
mod backends_updates;
mod background_admission;
mod bench;
mod bench_engine;
mod bench_lease;
mod body_limit;
mod candidate_alias_deferrals;
mod candidate_aliases;
mod candidate_routing;
mod capabilities_cloud;
mod capabilities_local;
mod capabilities_notes;
mod capabilities_override;
mod catalog_fields;
mod chat_actions;
mod chat_agent_live;
mod chat_archive;
mod chat_attach_hardening;
mod chat_attach_kinds;
mod chat_attachments;
mod chat_export;
mod chat_folders;
mod chat_golden;
mod chat_knowledge;
mod chat_live;
mod chat_replay_shapes;
mod chat_sampling;
mod chat_search;
mod chat_stt_settings;
mod chat_tab;
mod chat_temporary;
mod chat_thread_defaults;
mod chat_voice_audio_in;
mod chat_voice_dictation;
mod chat_voice_language;
mod chat_voice_language_rows;
mod chat_voice_language_turns;
mod chat_voice_reply_language;
mod chat_voice_resolve;
mod chat_voice_settings;
mod chat_voice_speak;
mod chat_voice_speak_ends;
mod chat_voice_speak_style;
mod chat_voice_speak_turns;
mod chat_voice_transcript;
mod chat_voice_warm_group;
mod chat_voice_writes;
mod config_hoisting;
mod count_compat;
mod create_clear;
mod dev_boot_prefix;
mod dev_models_dir;
mod e2e_proxy;
mod egress_adapters;
mod egress_golden;
mod embeddings_params;
mod gpu_contention;
mod hf_download;
mod image_backend;
mod image_lab;
mod image_live;
mod image_recipes;
mod ingress_roundtrip;
mod ingress_tool_results;
mod jobs;
mod key_policy;
mod key_set;
mod knowledge;
mod knowledge_hardening;
mod knowledge_limits;
mod knowledge_r3;
mod kv_unified_disable;
mod ladder_models;
mod llama_facts;
mod mcp_admin_plane;
mod mcp_ingress;
mod mcp_live;
mod mcp_selfadmin;
mod mcp_selfadmin_audio;
mod mcp_servers_route;
mod migrations;
mod model_runtime_overrides;
mod modelinfo_real_files;
mod models_endpoint;
mod openapi_coverage;
mod openapi_dashboard;
mod openapi_headers;
mod openapi_live;
mod openapi_ops;
mod openapi_structure;
mod openapi_v1;
mod ops_container;
mod owner_keys;
mod principal_gate;
mod quickdoc_docs_plane;
mod quickdoc_ingest;
mod realtime_audio_in;
mod realtime_barge;
mod realtime_barge_carry;
mod realtime_barge_reply;
mod realtime_barge_words;
mod realtime_batches;
mod realtime_cancel;
mod realtime_cancel_retry;
mod realtime_chat_thread;
mod realtime_cloud_stages;
mod realtime_conversation;
mod realtime_cues;
mod realtime_expressive;
mod realtime_half_duplex;
mod realtime_heard;
mod realtime_liveness;
mod realtime_mcp_calls;
mod realtime_mcp_cancel;
mod realtime_mcp_history;
mod realtime_mcp_listing;
mod realtime_mcp_protocol;
mod realtime_mcp_routing;
mod realtime_mcp_sent;
mod realtime_mcp_spoken;
mod realtime_mcp_turns;
mod realtime_pending;
mod realtime_protocol;
mod realtime_render;
mod realtime_response;
mod realtime_semantic;
mod realtime_session;
mod realtime_settings;
mod realtime_speakable;
mod realtime_speech;
mod realtime_tts_hold;
mod realtime_tts_residency;
mod realtime_turn;
mod realtime_turn_corpus;
mod realtime_voice;
mod realtime_voice_check;
mod realtime_warm;
mod realtime_written;
mod reasoning_live;
mod reasoning_off_fit;
mod responses_api;
mod responses_key_ref;
mod responses_mcp_spec;
mod route_golden;
mod route_walk;
mod router;
mod runtime_argv;
mod runtime_descriptor;
mod runtime_lifecycle;
mod runtime_llama_props;
mod runtime_ownership;
mod runtime_registry;
mod session_login;
mod tool_images;
mod tool_inventory;
mod ui_cache;
mod upstream_settle;
mod vram_admission;
mod web_pages;
