#!/usr/bin/env python3
"""Print the codepoints audio.cpp's NFKD table decomposes, as lmgw's Rust table.

Supertonic's tokenizer NFKD-normalises its text with a table generated into
audio.cpp (`src/framework/text/unicode_nfkd_data.inc`, Python's
`unicodedata` at one Unicode version) and looks every codepoint that comes
out up in its package's vocabulary. A codepoint the table does not have is
looked up as it is. lmgw's `unicode-normalization` crate decomposes at a
newer Unicode version, so `crates/lmgw-core/src/audio/families/charset/nfkd.rs`
carries the engine's own key set, which this prints from a clone of audio.cpp:

    scripts/audiocpp-nfkd-keys.py ~/src/audio.cpp \\
        > crates/lmgw-core/src/audio/families/charset/nfkd.rs && cargo fmt

Run it when audio.cpp regenerates the table (its header names the Unicode
version; the `nfkd` tests in that module say what changed). Read-only.
"""

import pathlib
import re
import subprocess
import sys


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__.strip().splitlines()[0], file=sys.stderr)
        print("usage: scripts/audiocpp-nfkd-keys.py <audio.cpp clone>", file=sys.stderr)
        return 2
    clone = pathlib.Path(sys.argv[1])
    inc = clone / "src/framework/text/unicode_nfkd_data.inc"
    text = inc.read_text(encoding="utf-8")
    version = re.search(r"Unicode data version: (\d+)\.(\d+)\.(\d+)", text)
    if not version:
        print(f"{inc}: no 'Unicode data version' line", file=sys.stderr)
        return 1
    entries = text.split("kNfkdEntries[]", 1)
    if len(entries) != 2:
        print(f"{inc}: no kNfkdEntries table", file=sys.stderr)
        return 1
    keys = sorted(int(m, 16) for m in re.findall(r"\{0x([0-9A-Fa-f]+),", entries[1]))
    if not keys:
        print(f"{inc}: kNfkdEntries is empty", file=sys.stderr)
        return 1
    rev = subprocess.run(
        ["git", "-C", str(clone), "rev-parse", "--short=7", "HEAD"],
        capture_output=True,
        text=True,
        check=False,
    ).stdout.strip() or "unknown"
    ranges: list[list[int]] = []
    for k in keys:
        if ranges and ranges[-1][1] + 1 == k:
            ranges[-1][1] = k
        else:
            ranges.append([k, k])
    major, minor, patch = version.groups()
    print(f"""//! The codepoints Supertonic's engine decomposes before its vocabulary
//! lookup: the keys of audio.cpp's NFKD table
//! (`src/framework/text/unicode_nfkd_data.inc` at {rev}, generated from
//! Python's `unicodedata` at Unicode {major}.{minor}.{patch}), {len(keys)} codepoints in
//! {len(ranges)} ranges. Generated by `scripts/audiocpp-nfkd-keys.py`; do not edit by
//! hand.

/// The Unicode version the engine's table was generated with.
pub(crate) const UNICODE: (u8, u8, u8) = ({major}, {minor}, {patch});

/// The codepoints the table has, as sorted inclusive ranges.
pub(crate) const DECOMPOSED: &[(u32, u32)] = &[""")
    for a, b in ranges:
        print(f"    (0x{a:04X}, 0x{b:04X}),")
    print("];")
    return 0


if __name__ == "__main__":
    sys.exit(main())
