//! Telemetry bus (§10): every request produces a `request_logs` row and a
//! broadcast event; the dashboard subscribes via SSE.

use std::collections::VecDeque;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Mutex;
use std::time::{Duration, Instant};

use serde::Serialize;
use tokio::sync::broadcast;

use crate::jobs::JobView;
use crate::mcp::McpStatusView;

#[derive(Debug, Clone, Serialize)]
pub struct RequestSummary {
    pub log_id: i64,
    /// Wall-clock time, RFC3339 UTC.
    pub ts: String,
    /// Name of the gateway API key that made the call (never the key itself);
    /// `None` when auth is disabled or the call was in-process.
    pub client_key: Option<String>,
    pub ingress_proto: String,
    pub requested_alias: String,
    pub upstream_name: Option<String>,
    pub upstream_model: Option<String>,
    pub egress_proto: Option<String>,
    pub status: u16,
    pub ttfb_ms: Option<i64>,
    pub total_ms: Option<i64>,
    pub prompt_tokens: Option<i64>,
    pub completion_tokens: Option<i64>,
    /// The cache subsets of `prompt_tokens` (usage-analytics §2.1). Carried on
    /// the live frame as well as the stored row, so a request that lands while
    /// the Traffic tab is open shows the same input split as it does after a
    /// reload. `None` = the provider reported no split.
    pub cached_in_tokens: Option<i64>,
    pub cache_write_tokens: Option<i64>,
    pub streamed: bool,
    pub error_kind: Option<String>,
    pub error_msg: Option<String>,
    /// What this request cost, in currency micro-units. `None` is **unpriced**,
    /// not free (usage-analytics §2.3) — the Traffic row shows a dash, and the
    /// Usage page counts it in the remainder it states beside every total.
    pub cost_micro: Option<i64>,
    pub class: String,
    /// `api_keys.id`, next to `client_key`'s name — a key-filtered live view
    /// filters on the id, and matching on the name would break the moment a
    /// key is renamed.
    pub key_id: Option<i64>,
    /// Why a fallback answered instead of the requested local model — the
    /// stored row's `fallback_reason`, so a live row reads like a reloaded
    /// one. `None` = no fallback.
    pub fallback_reason: Option<String>,
    /// The rung a ladder row answered from, 1-based — the stored row's
    /// `rung` (ladder design §6, migration 0043). `None` for a row without a
    /// ladder, and for a request its fallback answered.
    pub rung: Option<i64>,
}

#[derive(Debug, Clone)]
pub enum Event {
    Request(Box<RequestSummary>),
    /// Live MCP southbound connection status (§9) — drives the MCP tab's
    /// status badges. Carries the full set of connection views so a single
    /// frame refreshes the whole list.
    Mcp(Vec<McpStatusView>),
    /// Every currently-running background job (§9c). Like `Mcp`, the frame is
    /// the whole list: a job disappearing from it *is* the "it finished"
    /// signal, so consumers need no separate completion event.
    Jobs(Vec<JobView>),
    /// The GPU ledger and the admission queue (§9b). Pushed whenever a request
    /// starts or stops waiting for VRAM, so a queue that forms is visible the
    /// moment it forms rather than on the next poll tick.
    Vram(Box<crate::vram::VramView>),
    /// Every per-model container lmgw believes is up (per-model-containers
    /// §3.2/§3.4) — the successor of the shared router-mode `Router` frame §7
    /// deleted. Whole-list, like `Mcp`/`Jobs` — a model disappearing from it
    /// *is* the "it was stopped" signal.
    Runtime(Vec<crate::runtime::registry::RuntimeView>),
    /// The Backends nav badge's numbers (container-builds §8): builds with
    /// an update, registry images with a newer digest. Pushed when they can
    /// have changed — the check is periodic and in the background, and the
    /// dashboard polls nothing.
    Updates(lmgw_api_types::builds::UpdatesSummary),
}

/// Live counters for the dashboard.
#[derive(Debug, Clone, Default, PartialEq, Serialize)]
pub struct StatsView {
    pub total_requests: u64,
    pub total_errors: u64,
    pub prompt_tokens: u64,
    pub completion_tokens: u64,
    /// Requests in the trailing 60 s window.
    pub req_last_minute: u64,
    /// Errors in the trailing 60 s window.
    pub err_last_minute: u64,
    pub active_requests: i64,
    /// Output tokens per second generated by in-flight streams, measured over
    /// the trailing [`RATE_WINDOW`] (see [`RateWindow`]). `0.0` when nothing is
    /// streaming. Approximate for upstreams that batch several tokens into one
    /// SSE chunk, which is why the UI prefixes it with "~".
    pub tok_s: f64,
}

/// Trailing window the live output-token rate is measured over. Short enough
/// that the readout follows a stream's real speed and falls back to zero
/// promptly when it ends, long enough that per-chunk jitter doesn't make the
/// number flicker.
pub const RATE_WINDOW: Duration = Duration::from_secs(2);

/// Trailing-window estimate of the live output-token rate.
///
/// The hot path (every streamed chunk, on every concurrent stream) only bumps
/// one atomic counter — see [`TelemetryBus::note_stream_progress`]. The window
/// is reconstructed here from *samples of that counter*, taken whenever someone
/// reads the stats: while anything is in flight the SSE `events` handler does
/// that twice a second, which is exactly when the number is displayed.
///
/// Consequences of that shape, all deliberate:
/// - **Concurrent streams sum for free** — they share the one counter, so the
///   rate is the aggregate generation speed of the gateway, not of one request.
/// - **It decays on its own.** Once the counter stops moving, the newest and
///   oldest samples in the window carry the same total, so the rate reaches
///   exactly zero one window after the last token.
/// - **It needs two samples.** A single sample (first read, or the first read
///   after an idle gap longer than the window) reports `0.0` rather than
///   inventing a rate from an unbounded time span.
#[derive(Debug, Default)]
struct RateWindow {
    /// `(sampled at, cumulative output tokens at that moment)`, oldest first.
    samples: VecDeque<(Instant, u64)>,
}

impl RateWindow {
    /// Record that the cumulative counter read `total` at `now` and return the
    /// tokens/second over the trailing window. `now` is a parameter (not
    /// `Instant::now()`) so the behaviour is testable without sleeping.
    fn observe(&mut self, now: Instant, total: u64) -> f64 {
        if let Some(cutoff) = now.checked_sub(RATE_WINDOW) {
            while self.samples.front().is_some_and(|(t, _)| *t < cutoff) {
                self.samples.pop_front();
            }
        }
        let oldest = self.samples.front().copied();
        self.samples.push_back((now, total));
        let Some((t0, n0)) = oldest else {
            return 0.0; // nothing to measure against yet
        };
        let span = now.saturating_duration_since(t0).as_secs_f64();
        if span <= 0.0 {
            return 0.0;
        }
        // Round to one decimal: the counter is integral and the display shows
        // whole tokens, so the extra precision would only churn SSE frames.
        let rate = total.saturating_sub(n0) as f64 / span;
        (rate * 10.0).round() / 10.0
    }
}

#[derive(Default)]
struct Stats {
    total_requests: u64,
    total_errors: u64,
    prompt_tokens: u64,
    completion_tokens: u64,
    window: VecDeque<(Instant, bool)>, // (finish time, is_error)
    active: i64,
    /// Sampling state behind `tok_s`; guarded by the same lock as the counters
    /// so reading the stats takes one lock, not two.
    rate: RateWindow,
}

pub struct TelemetryBus {
    tx: broadcast::Sender<Event>,
    stats: Mutex<Stats>,
    /// Cumulative output tokens observed on streaming responses since start.
    /// Separate from `stats` (and from the per-request `completion_tokens`
    /// totals, which only move when a request *finishes*) because it is written
    /// from the streaming hot path, where a mutex would be wrong.
    stream_tokens: AtomicU64,
}

impl Default for TelemetryBus {
    fn default() -> Self {
        Self::new()
    }
}

/// Whether a `request_logs` row is model traffic that belongs in the token and
/// error-rate aggregates (§10, fix 2).
///
/// Excluded are the rows that represent a **tool call** rather than a model
/// call: they carry NULL tokens and a synthesized status, so folding them in
/// drags the dashboard's token totals and error rate toward nonsense. Both
/// tool-call producers are listed — the northbound `/mcp` `tools/call` path and
/// the `/v1/responses` loop's internal calls. Their *model* turns
/// (`"responses"`) and MCP sampling (`"mcp-sampling"`) are real LLM traffic with
/// real tokens and deliberately do count.
///
/// A caller whose proto is excluded here must also skip
/// [`TelemetryBus::request_started`], or `active` goes negative.
pub fn counts_in_token_stats(ingress_proto: &str) -> bool {
    !matches!(
        ingress_proto,
        "mcp" | RESPONSES_TOOL_PROTO | ADMIN_TOOL_PROTO | CHAT_TOOL_PROTO | AGENT_TOOL_PROTO
    )
}

/// What kind of work a logged request was (usage-analytics design §2.1).
///
/// The gateway has always known this implicitly — it is which handler ran — and
/// never written it down, so an embeddings call and a chat turn landed in the
/// same aggregate. They are not the same unit: an embed request is thousands of
/// input tokens and zero output, and averaging it into "tokens per request"
/// makes both numbers meaningless.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum RequestClass {
    /// A model turn: chat completions, legacy completions, `/v1/responses`,
    /// the dashboard's own chat, MCP sampling.
    #[default]
    Chat,
    /// An encoder call: `/v1/embeddings`, rerank.
    Aux,
    /// TTS / ASR / the generic audio task routes.
    Audio,
    /// An image (or video) generation call: `/v1/images/generations`,
    /// `/v1/images/edits`. Its own class because it has no tokens at all —
    /// averaging a two-second 1024² render into "tokens per request" would
    /// make that number mean even less than an embed call already does.
    Image,
    /// A tool *execution* row, not a model call — no tokens, synthesized status.
    Tool,
}

impl RequestClass {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Chat => "chat",
            Self::Aux => "aux",
            Self::Audio => "audio",
            Self::Image => "image",
            Self::Tool => "tool",
        }
    }

    pub fn from_label(s: &str) -> Self {
        match s {
            "aux" => Self::Aux,
            "audio" => Self::Audio,
            "image" => Self::Image,
            "tool" => Self::Tool,
            _ => Self::Chat,
        }
    }
}

/// Error kinds that mean *lmgw refused to do the work*, as opposed to an
/// upstream or a client failing. They get their own rollup outcome so "the
/// gateway said no" never reads as "the provider broke" — a month of
/// deliberate `gpu_hold` refusals would otherwise look like an outage.
pub const REFUSAL_KINDS: &[&str] = &[
    "gpu_hold",
    // A benchmark run holds the card (benchmark design §3.2): the hold's
    // twin, lmgw declining local work on purpose for the run's duration.
    "gpu_benchmark",
    // A background request deferred so as not to disturb the owner
    // (candidate-aliases design §4.3): lmgw declining work on purpose, like
    // the hold it answers as.
    "gpu_deferred",
    // An owner's candidate alias whose primary is unusable and nothing else
    // loaded (candidate-aliases design §4.2, §4.6): lmgw declining by its own
    // configuration, with no upstream involved — not an upstream error.
    "candidate_unavailable",
    "key_budget",
    "key_scope",
    // Concurrency refusals are `key_rate` too — same variant, different
    // `limit_kind` — because they clear the same way: by waiting.
    "key_rate",
    "key_expired",
    "body_limit",
    "vram",
];

/// The rollup's four-way outcome for one logged request.
pub fn outcome_of(status: i64, error_kind: Option<&str>) -> &'static str {
    if error_kind.is_some_and(|k| REFUSAL_KINDS.contains(&k)) {
        return "refused";
    }
    match status {
        200..=299 => "ok",
        400..=499 => "client_error",
        _ => "upstream_error",
    }
}

/// `ingress_proto` for a tool call made by the `/v1/responses` loop, as opposed
/// to `"responses"` for the model turns it runs between them.
pub const RESPONSES_TOOL_PROTO: &str = "responses-tool";

/// `ingress_proto` for a `/v1/responses` model turn.
pub const RESPONSES_PROTO: &str = "responses";

/// `ingress_proto` for an Admin Chat model turn (§21 stage 2). Real LLM traffic
/// with real tokens, so it counts — like `"chat"`, which it is a flavor of.
pub const ADMIN_PROTO: &str = "admin";

/// `ingress_proto` for an `lmgw__*` call Admin Chat made on the model's behalf.
/// A tool call: NULL tokens, synthesized status, excluded from the aggregates.
pub const ADMIN_TOOL_PROTO: &str = "admin-tool";

/// `ingress_proto` for an extraction turn made by a quickdoc ingest job
/// (quickdoc §8). Real LLM traffic with real tokens, so it counts — an
/// overnight ingest is exactly the kind of spend the dashboard should show. The
/// `emit_extraction` calls between the turns are executed in-process and write
/// no log rows at all — the job's own progress is where those are visible.
pub const INGEST_PROTO: &str = "quickdoc-ingest";

/// `ingress_proto` for a model turn made by a synthetic golden-query run
/// (quickdoc §10). Named apart from the ingest turns for the same reason those
/// are named apart from chat: the spend belongs to a run the owner started, and
/// Logs should say which one.
pub const GOLDEN_PROTO: &str = "quickdoc-golden";

/// `ingress_proto` for an embedding call quickdoc made in-process — an ingest
/// or re-embed batch, the probe that sizes a new corpus's vectors, or the query
/// half of a `docs__query` (quickdoc §3).
///
/// These ride [`crate::proxy::embed_in_process`] rather than the `/v1/embeddings`
/// handler, and for a long time that meant they were the one kind of model
/// traffic this gateway did not log: an overnight ingest showed its extraction
/// turns and nothing of the thousands of vectors it wrote. Real tokens, real
/// latency, real upstream — so it counts, like every other model call.
pub const EMBED_PROTO: &str = "quickdoc-embed";

/// `ingress_proto` for a rerank call quickdoc made in-process — the §6 rerank
/// stage of a query. Named apart from [`EMBED_PROTO`] because they are
/// different models doing different work, and "why is retrieval slow" is
/// answered by seeing which of the two the time went to.
pub const RERANK_PROTO: &str = "quickdoc-rerank";

/// `ingress_proto` for an MCP tool a Chat thread ran through its attached
/// servers. Same shape as the two above — no tokens, so it stays out of the
/// aggregates — and named apart from them so Logs shows which surface asked.
pub const CHAT_TOOL_PROTO: &str = "chat-tool";

/// `ingress_proto` for a model turn made by an agent run (agent-catalog §4.2):
/// a batch run's per-item classify call, and the model turns inside an apply
/// turn's tool loop. Real LLM traffic with real tokens, so it counts — a run
/// over fifty mails is exactly the spend the dashboard should show.
pub const AGENT_PROTO: &str = "agent";

/// `ingress_proto` for a tool call an agent run made (agent-catalog §4.3) — a
/// batch step's direct call, or one the apply turn's loop executed. A tool
/// call: NULL tokens, synthesized status, excluded from the aggregates, and
/// named apart from the model turns so Logs shows which half the time went to.
pub const AGENT_TOOL_PROTO: &str = "agent-tool";

/// The synthetic `internal:*` identity a gateway-internal consumer logs under
/// (usage-analytics design §4.4).
///
/// Admin Chat, dashboard Chat, corpus ingest, golden-query generation, the mail
/// workflow and the `/v1/responses` tool loop all spend real money on cloud
/// aliases and have always logged as "no key" — an unattended re-embed against
/// a cloud embedder could burn a budget with nothing in the dashboard to point
/// at. Mapping the `ingress_proto` label they already carry onto a row in
/// `api_keys` makes them visible and budgetable in one place, rather than
/// threading an identity through every in-process call site.
///
/// Public ingress (`openai` / `anthropic`) returns `None`: those carry a real
/// key, or no key at all when auth is off.
pub fn internal_identity(ingress_proto: &str) -> Option<&'static str> {
    Some(match ingress_proto {
        "chat" | CHAT_TOOL_PROTO => "internal:chat",
        ADMIN_PROTO | ADMIN_TOOL_PROTO => "internal:admin-chat",
        RESPONSES_PROTO | RESPONSES_TOOL_PROTO => "internal:responses",
        INGEST_PROTO => "internal:quickdoc-ingest",
        GOLDEN_PROTO => "internal:quickdoc-eval",
        EMBED_PROTO | RERANK_PROTO => "internal:quickdoc-query",
        // Migration 0031 renamed this identity row to `internal:agents` (the
        // agent catalog's §3): the retired mail workflow's spend history
        // carries over to the agents that replace it, so an install that ran it
        // keeps one continuous cost line across the cutover.
        AGENT_PROTO | AGENT_TOOL_PROTO => "internal:agents",
        "mcp-sampling" | "mcp" => "internal:mcp-sampling",
        _ => return None,
    })
}

impl TelemetryBus {
    pub fn new() -> Self {
        let (tx, _) = broadcast::channel(256);
        Self {
            tx,
            stats: Mutex::new(Stats::default()),
            stream_tokens: AtomicU64::new(0),
        }
    }

    pub fn subscribe(&self) -> broadcast::Receiver<Event> {
        self.tx.subscribe()
    }

    pub fn request_started(&self) {
        self.stats.lock().unwrap().active += 1;
    }

    /// Close out a [`request_started`](Self::request_started) that will never
    /// produce a row.
    ///
    /// The in-process encoder calls (`proxy::embed_once`, `proxy::rerank_once`)
    /// mark themselves in flight before resolving an alias, because resolving
    /// one can start a container and take real time. If that fails there is no
    /// upstream to key a `request_logs` row to, so nothing calls
    /// [`request_finished`](Self::request_finished) — and without this the
    /// gauge would go on counting a request that is over.
    pub fn request_abandoned(&self) {
        let mut s = self.stats.lock().unwrap();
        s.active = (s.active - 1).max(0);
    }

    /// Report `delta` newly generated output tokens on a stream that is still
    /// running — the input to the titlebar's live tok/s readout.
    ///
    /// This is the streaming hot path (called per relayed SSE chunk, on every
    /// concurrent stream), so it is exactly one relaxed atomic add: no lock, no
    /// allocation, no timestamp. All windowing happens on the read side in
    /// [`RateWindow`]. Relaxed ordering is right because the only consumer is a
    /// human-facing rate — it needs the value to arrive eventually, not to be
    /// ordered against other memory.
    ///
    /// Callers report *generated* tokens only (see `proxy::StreamProgress`);
    /// nothing here knows or cares which request they came from.
    pub fn note_stream_progress(&self, delta: u64) {
        if delta > 0 {
            self.stream_tokens.fetch_add(delta, Ordering::Relaxed);
        }
    }

    /// Record a finished request: update counters and broadcast.
    ///
    /// **MCP stats exclusion (§10, fix 2).** `ingress_proto = "mcp"` rows are
    /// `tools/call`s: their tokens are meaningless (NULL) and their HTTP status
    /// is synthesized (tool/JSON-RPC failures are mapped to a non-200 by the
    /// ingress, fix 1), so folding them into the token totals or the request /
    /// error-rate counters would skew the dashboard. They still get a
    /// `request_logs` row + a live SSE frame (so they show in the unified feed),
    /// they just don't move the aggregate. The `active`/`total_requests` count is
    /// also held back so the error *rate* denominator stays LLM-only.
    /// Note: `"mcp-sampling"` (M4) is deliberately **not** excluded — it is real
    /// LLM traffic with real tokens and should count.
    pub fn request_finished(&self, summary: RequestSummary) {
        let count_in_stats = counts_in_token_stats(&summary.ingress_proto);
        {
            let mut s = self.stats.lock().unwrap();
            if count_in_stats {
                // Only balance `active` for protos that called `request_started`;
                // the MCP `tools/call` path never increments it (it's excluded),
                // so decrementing here would push `active` negative.
                s.active = (s.active - 1).max(0);
                s.total_requests += 1;
                let is_err = summary.status >= 400;
                if is_err {
                    s.total_errors += 1;
                }
                s.prompt_tokens += summary.prompt_tokens.unwrap_or(0).max(0) as u64;
                s.completion_tokens += summary.completion_tokens.unwrap_or(0).max(0) as u64;
                s.window.push_back((Instant::now(), is_err));
                Self::trim(&mut s.window);
            }
        }
        let _ = self.tx.send(Event::Request(Box::new(summary)));
    }

    /// Broadcast the current MCP connection statuses to the live feed (§9).
    pub fn mcp_status(&self, views: Vec<McpStatusView>) {
        let _ = self.tx.send(Event::Mcp(views));
    }

    /// Broadcast the running background jobs to the live feed (§9c).
    pub fn vram(&self, view: crate::vram::VramView) {
        let _ = self.tx.send(Event::Vram(Box::new(view)));
    }

    pub fn jobs(&self, views: Vec<JobView>) {
        let _ = self.tx.send(Event::Jobs(views));
    }

    /// Broadcast the per-model container registry to the live feed (§3.2).
    pub fn runtime(&self, views: Vec<crate::runtime::registry::RuntimeView>) {
        let _ = self.tx.send(Event::Runtime(views));
    }

    /// Broadcast the update check's badge numbers (container-builds §8).
    pub fn updates(&self, summary: lmgw_api_types::builds::UpdatesSummary) {
        let _ = self.tx.send(Event::Updates(summary));
    }

    pub fn stats(&self) -> StatsView {
        self.stats_at(Instant::now())
    }

    /// Total streamed output tokens observed since start — the raw input to the
    /// rate window, exposed so the streaming paths can be tested on what they
    /// actually publish rather than on a time-dependent rate.
    #[cfg(test)]
    pub(crate) fn stream_tokens_total(&self) -> u64 {
        self.stream_tokens.load(Ordering::Relaxed)
    }

    /// [`Self::stats`] with the clock injected, so the rate window can be
    /// exercised in tests without sleeping.
    fn stats_at(&self, now: Instant) -> StatsView {
        // Sampling the counter *inside* the lock keeps the window's samples
        // monotonic in both time and total, even with several SSE readers.
        let total = self.stream_tokens.load(Ordering::Relaxed);
        let mut s = self.stats.lock().unwrap();
        Self::trim(&mut s.window);
        let tok_s = s.rate.observe(now, total);
        StatsView {
            total_requests: s.total_requests,
            total_errors: s.total_errors,
            prompt_tokens: s.prompt_tokens,
            completion_tokens: s.completion_tokens,
            req_last_minute: s.window.len() as u64,
            err_last_minute: s.window.iter().filter(|(_, e)| *e).count() as u64,
            active_requests: s.active,
            tok_s,
        }
    }

    fn trim(window: &mut VecDeque<(Instant, bool)>) {
        let cutoff = Instant::now() - Duration::from_secs(60);
        while window.front().is_some_and(|(t, _)| *t < cutoff) {
            window.pop_front();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ms(n: u64) -> Duration {
        Duration::from_millis(n)
    }

    /// The base case: a stream emitting 10 tokens every 500 ms reads as 20 tok/s
    /// once the window has something to measure against.
    #[test]
    fn rate_window_measures_tokens_per_second() {
        let t0 = Instant::now();
        let mut w = RateWindow::default();
        assert_eq!(w.observe(t0, 0), 0.0);
        assert_eq!(w.observe(t0 + ms(500), 10), 20.0);
        assert_eq!(w.observe(t0 + ms(1000), 20), 20.0);
        // Full window in view now (2 s back = t0), still the same speed.
        assert_eq!(w.observe(t0 + ms(2000), 40), 20.0);
        assert_eq!(w.observe(t0 + ms(2500), 50), 20.0);
    }

    /// A rate needs a span to divide by: the very first sample reports nothing
    /// rather than inventing a number from an unbounded time span.
    #[test]
    fn rate_window_first_sample_has_no_rate() {
        let t0 = Instant::now();
        let mut w = RateWindow::default();
        assert_eq!(w.observe(t0, 12_345), 0.0);
    }

    /// Samples older than the window are dropped, so a long idle gap can't be
    /// averaged over — the first read after it starts a fresh measurement.
    #[test]
    fn rate_window_ignores_samples_older_than_the_window() {
        let t0 = Instant::now();
        let mut w = RateWindow::default();
        w.observe(t0, 0);
        // Nothing read the stats for 5 s; the stale sample is not a baseline.
        assert_eq!(w.observe(t0 + ms(5000), 100), 0.0);
        assert_eq!(w.observe(t0 + ms(5500), 110), 20.0);
    }

    /// When a stream ends the counter stops moving, so the rate falls away as
    /// the last productive samples age out and is exactly 0 one window later.
    #[test]
    fn rate_window_decays_to_zero_after_a_stream_ends() {
        let t0 = Instant::now();
        let mut w = RateWindow::default();
        // 20 tok/s for 4 s, sampled twice a second.
        for i in 0..=8u64 {
            w.observe(t0 + ms(i * 500), i * 10);
        }
        // Stream over at t0+4 s with 80 tokens; the counter is frozen now.
        assert_eq!(w.observe(t0 + ms(4500), 80), 15.0); // (80-50)/2
        assert_eq!(w.observe(t0 + ms(5000), 80), 10.0); // (80-60)/2
        assert_eq!(w.observe(t0 + ms(5500), 80), 5.0); //  (80-70)/2
        assert_eq!(
            w.observe(t0 + ms(6000), 80),
            0.0,
            "one full window after the last token the rate must be exactly zero"
        );
    }

    /// Concurrent streams share the one counter, so the readout is the
    /// gateway's aggregate generation speed — two 10 tok/s streams read 20.
    #[test]
    fn stats_rate_sums_concurrent_streams() {
        let bus = TelemetryBus::new();
        let t0 = Instant::now();
        assert_eq!(bus.stats_at(t0).tok_s, 0.0);
        for i in 1..=4u64 {
            // Each "stream" reports 5 tokens per 500 ms tick, interleaved.
            bus.note_stream_progress(5);
            bus.note_stream_progress(5);
            let s = bus.stats_at(t0 + ms(i * 500));
            assert_eq!(s.tok_s, 20.0, "tick {i}");
        }
    }

    /// The counter is written from several stream tasks at once; the total has
    /// to be all of them, and the rate has to reflect that sum.
    #[test]
    fn stats_rate_counts_every_concurrent_writer() {
        let bus = std::sync::Arc::new(TelemetryBus::new());
        let t0 = Instant::now();
        bus.stats_at(t0);
        let mut handles = Vec::new();
        for _ in 0..4 {
            let bus = bus.clone();
            handles.push(std::thread::spawn(move || {
                for _ in 0..250 {
                    bus.note_stream_progress(1);
                }
            }));
        }
        for h in handles {
            h.join().unwrap();
        }
        // 4 × 250 tokens over a 1 s span.
        assert_eq!(bus.stats_at(t0 + ms(1000)).tok_s, 1000.0);
    }

    /// Only streaming progress feeds the live rate. A finished non-streaming
    /// request moves the cumulative token totals and nothing else, so the
    /// titlebar doesn't invent a speed for a request that never streamed.
    #[test]
    fn stats_rate_ignores_non_streaming_traffic() {
        let bus = TelemetryBus::new();
        let t0 = Instant::now();
        bus.stats_at(t0);
        bus.request_started();
        bus.request_finished(RequestSummary {
            log_id: 1,
            ts: "2026-01-01T00:00:00Z".into(),
            client_key: None,
            ingress_proto: "openai".into(),
            requested_alias: "a".into(),
            upstream_name: None,
            upstream_model: None,
            egress_proto: None,
            status: 200,
            ttfb_ms: Some(5),
            total_ms: Some(10),
            prompt_tokens: Some(100),
            completion_tokens: Some(400),
            cached_in_tokens: None,
            cache_write_tokens: None,
            streamed: false,
            error_kind: None,
            error_msg: None,
            cost_micro: Some(1_500),
            class: "chat".into(),
            key_id: None,
            fallback_reason: None,
            rung: None,
        });
        let s = bus.stats_at(t0 + ms(500));
        assert_eq!(s.completion_tokens, 400);
        assert_eq!(s.tok_s, 0.0);
        assert_eq!(s.active_requests, 0);
    }
}
